In [6]:
import numpy as np
grades = [
    [85,78,92,88],
    [70,76,80,65],
    [90,88,94,91],
    [60,65,58,62],
    [100,95,98,97]
]
Grades = np.array(grades)
print("Shape : ", Grades.shape)
student_mean=Grades.mean(axis=1)
print("Mean for each student : ",student_mean)
print("Mean for each subject : " , Grades.mean(axis=0))
print("Students whose average grade is greater than 85 :\n " , Grades[student_mean>85])
print("After bonus : \n" ,Grades+5)
min=Grades.min(axis=0)
max=Grades.max(axis=0)
normalized_grades = (Grades - min)/(max - min)
print("After normalization : \n" ,normalized_grades)
Flatten_grades=Grades.reshape(-1)
print("Flatten : \n" , Flatten_grades)

Shape :  (5, 4)
Mean for each student :  [85.75 72.75 90.75 61.25 97.5 ]
Mean for each subject :  [81.  80.4 84.4 80.6]
Students whose average grade is greater than 85 :
  [[ 85  78  92  88]
 [ 90  88  94  91]
 [100  95  98  97]]
After bonus : 
 [[ 90  83  97  93]
 [ 75  81  85  70]
 [ 95  93  99  96]
 [ 65  70  63  67]
 [105 100 103 102]]
After normalization : 
 [[0.625      0.43333333 0.85       0.74285714]
 [0.25       0.36666667 0.55       0.08571429]
 [0.75       0.76666667 0.9        0.82857143]
 [0.         0.         0.         0.        ]
 [1.         1.         1.         1.        ]]
Flatten : 
 [ 85  78  92  88  70  76  80  65  90  88  94  91  60  65  58  62 100  95
  98  97]


In [17]:
x = [50,60,80,100,120]
y = [150,180,240,300,330]
house_size = np.array(x)
house_size = house_size[: , np.newaxis]
price = np.array(y)
one = np.ones((5,1))
bais_x = np.concatenate((one,house_size),axis=1)
theta = (np.linalg.inv(((bais_x.T)@bais_x))) @ ((bais_x.T)@price)
new_pred = np.array([1,90])
pred = new_pred@theta
print(pred)


261.21951219512164
